version: '3.4'

services:
  app:
    container_name: directory-lister-app
    build: .
    image: phlak/directory-lister:dev
    restart: unless-stopped
    depends_on:
      - memcached
      - redis
    # ports:
    #   - ${APP_PORT:-80}:80
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP:-172.17.0.1}
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
    volumes:
      - /data/public:/var/www/html
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache2/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    labels:
      traefik.enable: "true"
      traefik.http.routers.directoryLister.entryPoints: web
      traefik.http.routers.directoryLister.tls.certResolver: default
      traefik.http.routers.directoryLister.rule: Host(`public.example.com`)

  memcached:
    container_name: directory-lister-memcached
    image: memcached:1.6
    restart: unless-stopped
    ports:
      - ${MEMCACHED_PORT:-11211}:11211

  redis:
    container_name: directory-lister-redis
    image: redis:6.0
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379

  # npm:
  #   container_name: directory-lister-npm
  #   image: phlak/directory-lister:dev
  #   volumes:
  #     - ./:/var/www/html
  #   user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
  #   command: npm run watch

networks:
  web:
    external: true
